title: Cameron Harper
author: Cameron Harper
email: contact@cjh.id.au

markdown: kramdown
theme: minima

google_analytics: UA-39608896-1

github_username:  cjhdev
linkedin_username: cameronisanengineer

plugins:
  - jekyll-toc
  - jekyll-seo-tag

destination: docs

description: Cameron's wicked awesome personal page
